apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-survey-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: student-survey
  template:
    metadata:
      labels:
        app: student-survey
    spec:
      containers:
      - name: student-survey-container
        image: vrishin/student-survey-app:0.1
        ports:
        - containerPort: 5000
