apiVersion: v1
kind: Service
metadata:
  name: student-survey-service
spec:
  selector:
    app: student-survey
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 80
  type: LoadBalancer
